global:
  scrape_interval: 3m
scrape_configs:
  - job_name: 'apache'
    static_configs:
      - targets: ['web_server:80']
scrape_configs:
  - job_name: 'hyper-v'
    static_configs:
      - targets: ['10.210.40.180:9182']